server:
  port: ${MDM_PORT:8083}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: mdm
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: dev
    password: Ab123456
    hikari:
      schema: mdm
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: 195.93.252.91:29092
    producer:
      acks: all
    consumer:
      group-id: prusakova-mdm-group
  cloud:
    openfeign:
      client:
        config:
          mdm-client:
            connect-timeout: 5000
            read-timeout: 5000

mdm:
  system-id: mdm-prusakova
  sender: prusakova
  kafka:
    mdm-change-phone:
      enabled: true
      topic-in: MDM.Change.Phone.IN.V1
  integration:
    change-phone:
      host-one: http://localhost:8082
      host-two: http://localhost:8082
  retry:
    max-attempts: 2
    backoff: 1000